-- # Write your MySQL query statement below
-- SELECT C.NAME AS CUSTOMERS FROM CUSTOMERS C
-- JOIN ORDERS O ON C.ID = O.CUSTOMERID
-- WHERE C.ID NOT IN (O.CUSTOMERID);
SELECT C.NAME AS Customers
FROM Customers C
LEFT JOIN Orders O
ON C.ID = O.CUSTOMERID
WHERE O.CUSTOMERID IS NULL;